//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceItUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayerProfile()
        {
            this.Matches = new HashSet<Match>();
        }
    
        public int player_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string gender { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<int> profile_level { get; set; }
        public string description { get; set; }
        public Nullable<decimal> feedback { get; set; }
        public string avatar_path { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual PlayerLogin PlayerLogin { get; set; }
        public virtual ProfileTitle ProfileTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Matches { get; set; }
    }
}
